/**
 * Airline names for the carriers that show up most often in global results.
 * Unknown codes fall back to the code itself rather than a guessed name; the
 * live adapter can also enrich this from the Travelpayouts airline directory.
 */
export const AIRLINES: Record<string, string> = {
  AI: "Air India",
  IX: "Air India Express",
  UK: "Vistara",
  "6E": "IndiGo",
  SG: "SpiceJet",
  QP: "Akasa Air",
  EK: "Emirates",
  FZ: "flydubai",
  EY: "Etihad Airways",
  QR: "Qatar Airways",
  GF: "Gulf Air",
  WY: "Oman Air",
  SV: "Saudia",
  KU: "Kuwait Airways",
  TK: "Turkish Airlines",
  SQ: "Singapore Airlines",
  TR: "Scoot",
  MH: "Malaysia Airlines",
  AK: "AirAsia",
  TG: "Thai Airways",
  FD: "Thai AirAsia",
  VJ: "VietJet Air",
  VN: "Vietnam Airlines",
  CX: "Cathay Pacific",
  BR: "EVA Air",
  CI: "China Airlines",
  JL: "Japan Airlines",
  NH: "ANA",
  KE: "Korean Air",
  OZ: "Asiana Airlines",
  GA: "Garuda Indonesia",
  QZ: "Indonesia AirAsia",
  PR: "Philippine Airlines",
  UL: "SriLankan Airlines",
  BA: "British Airways",
  VS: "Virgin Atlantic",
  AF: "Air France",
  KL: "KLM",
  LH: "Lufthansa",
  LX: "SWISS",
  OS: "Austrian Airlines",
  SN: "Brussels Airlines",
  IB: "Iberia",
  VY: "Vueling",
  TP: "TAP Air Portugal",
  AZ: "ITA Airways",
  SK: "SAS",
  AY: "Finnair",
  EI: "Aer Lingus",
  LO: "LOT Polish Airlines",
  OK: "Czech Airlines",
  A3: "Aegean Airlines",
  FR: "Ryanair",
  U2: "easyJet",
  W6: "Wizz Air",
  AA: "American Airlines",
  DL: "Delta Air Lines",
  UA: "United Airlines",
  B6: "JetBlue",
  AS: "Alaska Airlines",
  WN: "Southwest Airlines",
  AC: "Air Canada",
  WS: "WestJet",
  AM: "Aeroméxico",
  LA: "LATAM Airlines",
  AD: "Azul",
  G3: "Gol",
  AR: "Aerolíneas Argentinas",
  AV: "Avianca",
  CM: "Copa Airlines",
  QF: "Qantas",
  JQ: "Jetstar",
  VA: "Virgin Australia",
  NZ: "Air New Zealand",
  SA: "South African Airways",
  KQ: "Kenya Airways",
  ET: "Ethiopian Airlines",
  MS: "EgyptAir",
  AT: "Royal Air Maroc",
  LY: "El Al",
  RJ: "Royal Jordanian",
};

export function airlineName(code: string): string {
  return AIRLINES[code.toUpperCase()] ?? code.toUpperCase();
}
