import type { Metadata } from "next";

import { LegalPage } from "@/components/common/legal-page";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Privacy",
  description: `How ${siteConfig.name} handles data. Placeholder content pending legal review.`,
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy" updated="September 2026">
      <section>
        <h2>What this service does</h2>
        <p>
          {siteConfig.name} is a travel search service. You search for flights and hotels here, and
          we send you to a travel partner&apos;s website to complete any booking. There is no
          account to create, no password to set and no booking held on this site.
        </p>
      </section>

      <section>
        <h2>What we collect</h2>
        <ul>
          <li>
            <strong>Search details</strong> — the route, dates, number of travellers and currency
            you searched for, so we can return results and understand which searches are popular.
          </li>
          <li>
            <strong>Anonymous usage events</strong> — which filters and sort options are used, and
            when a link to a travel partner is clicked. These carry a random identifier scoped to
            your browser session, not to you.
          </li>
          <li>
            <strong>Standard server logs</strong> — generated by our hosting provider when your
            browser requests a page.
          </li>
        </ul>
        <p>
          We do not ask for your name, email address, phone number or payment details, and we have
          no way to collect them: this site takes no bookings and no payments.
        </p>
      </section>

      <section>
        <h2>Travel partners</h2>
        <p>
          When you choose a deal, we redirect you to a travel partner. From that point the
          partner&apos;s own privacy policy applies to anything you enter on their site. We pass an
          affiliate identifier so the partner can attribute the visit to us; we do not pass any
          information about you.
        </p>
      </section>

      <section>
        <h2>Cookies and storage</h2>
        <p>
          We store your chosen display currency in a cookie so it persists between visits, and a
          random session identifier in your browser&apos;s session storage for anonymous analytics.
          We also use Vercel Web Analytics to count page views and measure page speed: it sets no
          cookies of its own, does not follow you to other sites, and its requests are served from
          this domain. The application is built so that a consent mechanism can be added before any
          additional or third-party tracking is introduced.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          Questions about this page can go to {siteConfig.contactEmail}. The address and the wording
          above are placeholders to be confirmed during legal review.
        </p>
      </section>
    </LegalPage>
  );
}
